<?php

/*
|--------------------------------------------------------------------------
| Settings defaults
|--------------------------------------------------------------------------
| Each top-level key is a settings group stored as one row. Values saved
| from the dashboard are merged over these defaults; "reset" restores them.
*/

$t = fn (string $ar, string $en) => ['ar' => $ar, 'en' => $en];

$seoPage = fn (string $ar, string $en, string $headingAr, string $headingEn) => [
    'title' => $t("فراس المجد | {$ar}", "Firas Al Majd | {$en}"),
    'description' => $t("شركة فراس المجد العمرانية — {$ar} خدمات المقاولات والتشطيبات والنقل والتوريد والLandscape والصيانة في الرياض", "Firas Al Majd Urban Company — {$en}. Construction, fit-out, infrastructure, logistics and landscaping services in Riyadh."),
    'keywords' => $t('', ''),
    'og_image' => '',
    'heading' => $t($headingAr, $headingEn),
    'noindex' => false,
];

return [

    'general' => [
        'site_name' => $t('فراس المجد', 'Firas Al Majd'),
        'company_name' => $t('شركة فراس المجد العمرانية', 'Firas Al Majd Urban Company'),
        'tagline' => $t('تخصصات عدة ورؤية واحدة', 'Multiple disciplines. One vision.'),
        'logo' => 'seed/logo-stacked.png',
        'logo_alt' => $t('Firas Al Majd — Construction & Development', 'Firas Al Majd — Construction & Development'),
        'footer_logo' => 'seed/logo-stacked.png',
        'favicon' => 'seed/brand-mark.png',
        'loader_enabled' => true,
        'loader_logo' => 'seed/logo-stacked.png',
        'phone' => '+966503371820',
        'phone_display' => '+966 50 337 1820',
        'whatsapp' => '966503371820',
        'whatsapp_float_show' => true,
        'whatsapp_float_side' => 'right',
        'whatsapp_float_message' => ['ar' => '', 'en' => ''],
        'email_primary' => 'FIRAS-CH@FIRASALMAJD.COM',
        'email_secondary' => 'projects@firasalmajd.com',
        'cr_number' => '7054600239',
        'po_box' => '',
        'address' => $t("حي الملك عبدالعزيز، شارع ابن كثير\nالرياض 12233، المملكة العربية السعودية", "King Abdulaziz District, Ibn Katheer St.\nRiyadh 12233, Saudi Arabia"),
        'map_query' => 'King Abdulaziz District Ibn Katheer Riyadh 12233',
        'header_button_show' => true,
        'header_button_text' => $t('تواصل معنا', 'Contact us'),
        'header_button_url' => 'route:contact',
        'footer_social_title' => $t('تواصل معنا', 'Connect with us'),
        'copyright' => $t('شركة فراس المجد العمرانية جميع الحقوق محفوظة', 'Firas Al Majd Urban Company. All rights reserved.'),
        'social' => [
            ['platform' => 'facebook', 'url' => '', 'enabled' => true],
            ['platform' => 'instagram', 'url' => '', 'enabled' => true],
            ['platform' => 'tiktok', 'url' => '', 'enabled' => true],
            ['platform' => 'snapchat', 'url' => '', 'enabled' => true],
            ['platform' => 'x', 'url' => '', 'enabled' => true],
            ['platform' => 'linkedin', 'url' => '', 'enabled' => true],
        ],
        'whatsapp_contact_template' => $t(
            "مرحبًا فراس المجد، أرغب في مناقشة مشروع.\nالاسم: {name}\nالجوال: {phone}\nالبريد الإلكتروني: {email}\nالخدمة: {service}\nتفاصيل المشروع: {message}",
            "Hello Firas Al Majd, I would like to discuss a project.\nName: {name}\nPhone: {phone}\nEmail: {email}\nService: {service}\nProject brief: {message}"
        ),
        'whatsapp_career_template' => $t(
            "مرحبًا فراس المجد، أرغب في التقديم على وظيفة\nالوظيفة: {job}\nالاسم: {name}\nالجوال: {phone}\nالبريد: {email}\nسنوات الخبرة: {experience}\nنبذة: {summary}",
            "Hello Firas Al Majd, I would like to apply for a position\nPosition: {job}\nName: {name}\nPhone: {phone}\nEmail: {email}\nYears of experience: {experience}\nProfile: {summary}"
        ),
        'notify_email' => '',
    ],

    'seo' => [
        'site_name' => $t('فراس المجد', 'Firas Al Majd'),
        'alternate_name' => $t('شركة فراس المجد العمرانية', 'Firas Al Majd Urban Company'),
        'default_description' => $t('شركة فراس المجد العمرانية — نبني اليوم نصنع الأثر خدمات المقاولات والتشطيبات والنقل والتوريد والLandscape والصيانة في الرياض', 'Firas Al Majd Urban Company — integrated construction, fit-out, infrastructure, logistics and landscaping services in Riyadh.'),
        'default_keywords' => $t('مقاولات الرياض, تشطيبات, بنية تحتية, تنسيق مواقع, صيانة, فراس المجد', 'Riyadh construction, fit-out, infrastructure, landscaping, maintenance, Firas Al Majd'),
        'title_separator' => ' | ',
        'og_image' => 'seed/hero.webp',
        'search_logo' => 'seed/brand-mark.png',
        'twitter_site' => '',
        'organization_type' => 'GeneralContractor',
        'google_verification' => '',
        'bing_verification' => '',
        'yandex_verification' => '',
        'indexing' => true,
        'sitemap_enabled' => true,
        'robots_extra' => '',
        'geo_region' => 'SA-01',
        'geo_placename' => 'Riyadh',
        'pages' => [
            'home' => $seoPage('نبني اليوم نصنع الأثر', 'Building today. Shaping tomorrow.', 'شركة فراس المجد العمرانية', 'Firas Al Majd Urban Company'),
            'about' => $seoPage('من نحن', 'About us', 'من نحن', 'About us'),
            'services' => $seoPage('خدماتنا', 'Our services', 'خدماتنا', 'Our services'),
            'projects' => $seoPage('المشاريع', 'Projects', 'المشاريع', 'Projects'),
            'gallery' => $seoPage('معرض الصور', 'Gallery', 'معرض الصور', 'Gallery'),
            'certificates' => $seoPage('الشهادات المعتمدة', 'Certifications', 'الشهادات المعتمدة', 'Certifications'),
            'careers' => $seoPage('الوظائف', 'Careers', 'الوظائف', 'Careers'),
            'approach' => $seoPage('رؤيتنا', 'Our vision', 'رؤيتنا', 'Our vision'),
            'contact' => $seoPage('تواصل معنا', 'Contact us', 'تواصل معنا', 'Contact us'),
        ],
    ],

    'pixels' => [
        'meta_pixel_id' => '',
        'ga4_id' => '',
        'gtm_id' => '',
        'google_ads_id' => '',
        'google_ads_lead_label' => '',
        'tiktok_pixel_id' => '',
        'snapchat_pixel_id' => '',
        'x_pixel_id' => '',
        'linkedin_partner_id' => '',
        'pinterest_tag_id' => '',
        'clarity_id' => '',
        'track_leads' => true,
        'custom_head' => '',
        'custom_body' => '',
    ],

    'login' => [
        'background_image' => 'seed/hero.webp',
        'background_opacity' => 100,
        'overlay_color' => '#141715',
        'overlay_opacity' => 62,
        'background_blur' => 0,
        'show_logo' => true,
        'logo' => 'seed/logo-stacked.png',
        'logo_width' => 150,
        'title' => $t('تسجيل الدخول', 'Sign in'),
        'subtitle' => $t('لوحة تحكم موقع فراس المجد', 'Firas Al Majd website control panel'),
        'card_bg' => '#231f20',
        'card_opacity' => 88,
        'card_blur' => 10,
        'card_border_color' => '#c9a32d',
        'card_border_width' => 2,
        'card_radius' => 4,
        'card_width' => 430,
        'card_text' => '#f8f7f3',
        'card_muted' => '#b9b2a3',
        'label_color' => '#dfbd5b',
        'input_bg' => '#ffffff',
        'input_bg_opacity' => 6,
        'input_text' => '#ffffff',
        'input_border' => '#6d655a',
        'input_focus' => '#c9a32d',
        'input_radius' => 0,
        'button_text' => $t('دخول', 'Sign in'),
        'button_bg' => '#c9a32d',
        'button_color' => '#231f20',
        'button_hover_bg' => '#dfbd5b',
        'button_radius' => 0,
        'show_remember' => true,
        'footer_text' => $t('© شركة فراس المجد العمرانية', '© Firas Al Majd Urban Company'),
    ],

    'dashboard' => [
        'name' => $t('لوحة التحكم', 'Control panel'),
        'logo' => 'seed/logo-stacked.png',
        'favicon' => 'seed/brand-mark.png',
        'per_page' => 15,
        'default_locale' => 'ar',
        'notifications_poll' => 30,
        'date_format' => 'Y-m-d',
        'show_welcome' => true,
    ],

    'theme_admin' => [
        'accent' => '#c9a32d',
        'accent_text' => '#231f20',
        'primary' => '#231f20',
        'primary_text' => '#ffffff',
        'sidebar_bg' => '#1f1b1a',
        'sidebar_text' => '#bdb6ab',
        'sidebar_heading' => '#7b746a',
        'sidebar_active_bg' => '#2c2726',
        'sidebar_active_text' => '#dfbd5b',
        'topbar_bg' => '#ffffff',
        'topbar_text' => '#231f20',
        'body_bg' => '#f3f1eb',
        'card_bg' => '#ffffff',
        'border' => '#e2ddd1',
        'text' => '#231f20',
        'muted' => '#7a746b',
        'table_head_bg' => '#faf8f3',
        'success' => '#3f7a50',
        'danger' => '#b0412e',
        'warning' => '#b4822a',
        'info' => '#3d6a80',
        'radius' => 4,
        'font_size' => 14,
        'sidebar_width' => 262,
    ],

    'theme_site' => [
        'ink' => '#231f20',
        'gold' => '#c9a32d',
        'gold_light' => '#dfbd5b',
        'paper' => '#f8f7f3',
        'muted' => '#77736e',
        'line' => '#dedbd4',
    ],
];
